### ISSUE TITLE
Documentação básica de Markdown

### ISSUE THREAD

**Issue by F4NT0** [F4NT0/Documentation-as-code#1]
- [ ] Colocando títulos (#3)
- [ ] Como colocar em bold (#4)
- [ ] Como colocar em italico (#4)
- [ ] Como colocar um link (#10)
- [ ] Como colocar uma imagem usando markdown (#5)
- [ ] Como criar uma tabela em markdown (#8)
- [ ] Como colocar código em markdown (#6)
- [ ] Como colocar emojis em arquivos markdown
- [ ] Como colocar tópicos em markdown (#7)
- [ ] Como colocar citações em markdown (#9)
- [ ] Como dividir as informações em markdown (#11)
